import './globals.css';
import Nav from '@/components/Nav';

export const metadata = {
  title: "Jeffrey Li's Website",
  description: 'Generated by create-next-app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className="p-4">
        <Nav />
        {children}
      </body>
    </html>
  )
}
