import './globals.css';
import Nav from '@/components/Nav';

export const metadata = {
  title: "Jeffrey Li",
  description: 'Generated by create-next-app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className="p-5 pt-12 md:p-10">
        <Nav />
        <div className="lg:flex lg:justify-center lg:relative">
          {children}
        </div>
      </body>
    </html>
  )
}
